apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-internal
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
  generation: 1
  name: prometheus-server
  namespace: monitoring
spec:
  backend:
    serviceName: prometheus-server
    servicePort: 80
  rules:
  - host: prometheus-server.<company-name>.internal
    http:
      paths:
      - backend:
          serviceName: prometheus-server
          servicePort: 80
        path: /
